export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  BRANCH_MANAGER: "BRANCH_MANAGER",
  SALES_MANAGER: "SALES_MANAGER",
  SALES_EXECUTIVE: "SALES_EXECUTIVE",
  INVENTORY_MANAGER: "INVENTORY_MANAGER",
  ACCOUNTANT: "ACCOUNTANT",
  KARIGAR_MANAGER: "KARIGAR_MANAGER",
  VIEWER: "VIEWER",
};

export const PERMISSIONS = {
  VIEW_DASHBOARD: "view:dashboard",
  UPDATE_GOLD_RATE: "update:gold_rate",
  MANAGE_INVENTORY: "manage:inventory",
  CREATE_SALE: "create:sale",
  MANAGE_USERS: "manage:users",
  VIEW_REPORTS: "view:reports",
  MANAGE_BRANCHES: "manage:branches",
  MANAGE_KARIGAR: "manage:karigar",
  MANAGE_FINANCE: "manage:finance",
};

const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.BRANCH_MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.UPDATE_GOLD_RATE,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.CREATE_SALE,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_KARIGAR,
  ],
  [ROLES.SALES_MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.CREATE_SALE,
    PERMISSIONS.VIEW_REPORTS,
  ],
  [ROLES.SALES_EXECUTIVE]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.CREATE_SALE,
  ],
  [ROLES.INVENTORY_MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.UPDATE_GOLD_RATE,
  ],
  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_FINANCE,
    PERMISSIONS.VIEW_REPORTS,
  ],
  [ROLES.KARIGAR_MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_KARIGAR,
    PERMISSIONS.MANAGE_INVENTORY,
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.VIEW_DASHBOARD,
  ],
};

export function hasPermission(role, permission) {
  if (!role) return false;
  const permissions = ROLE_PERMISSIONS[role] || [];
  return permissions.includes(permission);
}
